Align output colors for all tools #130
projectdiscovery/pdtm pull request #131
Opened 2023-05-02 09:30 UTC by edoardottt

This PR closes #130.

2023-05-02 11:56 UTC, ehsandeep approved these changes

2023-05-02 18:33 UTC, ShubhamRasal requested changes
Thanks for raising issue and  PR @edoardottt 
suggesting small change to make it more readable.

2023-05-02 18:33 UTC, ShubhamRasal commented on pkg/utils/utils.go
> +			msg = "(" + au.Gray(10, "not supported").String() + ")"
we can use fmt.Sprintf to make it more readable
```go
msg = fmt.Sprintf("(%s)", au.Gray(10, "not supported").String())
```

2023-05-02 18:33 UTC, ShubhamRasal commented on pkg/utils/utils.go
> +			msg = "(" + au.BrightYellow("not installed").String() + ")"
```go
msg = fmt.Sprintf("(%s)", au.BrightYellow("not installed").String())
```

2023-05-02 18:33 UTC, ShubhamRasal commented on pkg/utils/utils.go
> +			msg = "(" + au.BrightGreen("latest").String() + ") (" + au.BrightGreen(tool.Version).String() + ")"
```go
msg = fmt.Sprintf("(%s) (%s)", au.BrightGreen("latest").String(), au.BrightGreen(tool.Version).String())
```

2023-05-02 18:33 UTC, ShubhamRasal commented on pkg/utils/utils.go
> +			msg = "(" + au.Red("outdated").String() + ") (" +
```go
msg = fmt.Sprintf("(%s) (%s) ➡ (%s)", au.Red("outdated").String(), au.Red(installedVersionString).String(), au.BrightGreen(tool.Version).String())
```

2023-05-03 08:17 UTC, ShubhamRasal approved these changes

2023-05-03 08:36 UTC, merged