print requirement info
projectdiscovery/pdtm pull request #166
Opened 2023-06-19 15:28 UTC by dogancanbakir

This PR prints tool requirement info for given tools. Closes #6.

2023-06-21 01:28 UTC, Mzack9999 requested changes
suggesting `fmt.xxx` => `gologger`

2023-06-21 01:28 UTC, Mzack9999 commented on internal/runner/runner.go
> +			fmt.Printf("%s\n", au.Bold(tool.Name+" requirements:").String())
I think we should stick to `gologger` if it's not causing issues with coloring

2023-06-21 01:28 UTC, Mzack9999 commented on internal/runner/runner.go
> +		fmt.Printf("%s %s\n", isRequired, instruction)
same here

2023-06-21 19:24 UTC, Mzack9999 requested changes
It seems like there is some issue with deps detection on osx:
```
$ ./pdtm -i naabu

                ____          
     ____  ____/ / /_____ ___ 
    / __ \/ __  / __/ __ __  \
   / /_/ / /_/ / /_/ / / / / /
  / .___/\__,_/\__/_/ /_/ /_/ 
 /_/                         

                projectdiscovery.io

[INF] Current pdtm version v0.0.7 (latest)
[INF] Run `source ~/.bashrc` to add /Users/marcornvh/.pdtm/go/bin to $PATH 
[INF] installing naabu...
[INF] installed naabu 2.1.6 (latest)
[INF] naabu requirements:
required To install libpcap on macOS, run the following command in the terminal: sudo brew install libpcap
$ brew install libpcap
Warning: libpcap 1.10.4 is already installed and up-to-date.
```

We can try a more straightforward strategy, like executing the binary just downloaded and checking the output for errors, then suggesting how to install deps. What do you think?

2023-06-22 07:54 UTC, dogancanbakir commented
> It seems like there is some issue with deps detection on osx:
> 
> ```
> $ ./pdtm -i naabu
> 
>                 ____          
>      ____  ____/ / /_____ ___ 
>     / __ \/ __  / __/ __ __  \
>    / /_/ / /_/ / /_/ / / / / /
>   / .___/\__,_/\__/_/ /_/ /_/ 
>  /_/                         
> 
>                 projectdiscovery.io
> 
> [INF] Current pdtm version v0.0.7 (latest)
> [INF] Run `source ~/.bashrc` to add /Users/marcornvh/.pdtm/go/bin to $PATH 
> [INF] installing naabu...
> [INF] installed naabu 2.1.6 (latest)
> [INF] naabu requirements:
> required To install libpcap on macOS, run the following command in the terminal: sudo brew install libpcap
> $ brew install libpcap
> Warning: libpcap 1.10.4 is already installed and up-to-date.
> ```
> 
> We can try a more straightforward strategy, like executing the binary just downloaded and checking the output for errors, then suggesting how to install deps. What do you think?

It appears that the issue may be related to the naming and extension convention specific to the operating system. See https://github.com/projectdiscovery/utils/blob/main/syscallutil/syscallutil_test.go#L15 for more information. We can proceed with your suggestion as it seems more convenient.

2023-06-28 07:35 UTC, Mzack9999 commented
@dogancanbakir I think we can improve the multi-platform check and make it more precise with additional steps (like running the tool and seeing if any error gets printed to stdout/stderr - as previously mentioned. I changed red to yellow for now since the missing dependency might prevent the tool from running under certain conditions but not being installed as we are downloading the binary directly.

2023-06-28 07:35 UTC, Mzack9999 approved these changes

2023-07-14 13:08 UTC, ehsandeep approved these changes

2023-07-14 13:09 UTC, merged