send protected machineid
projectdiscovery/pdtm pull request #197
Opened 2023-09-13 10:33 UTC by dogancanbakir

Closes #196

2023-09-21 16:09 UTC, tarunKoyalwar requested changes
@dogancanbakir , originally we were thinking of using `machineID` in all pd tools and this can be achieved easily without updating all tools if we generate and add machineID here https://github.com/projectdiscovery/utils/blob/8b5a952c13df89a599e8e97a5e47542ac9a49547/update/update.go#L148-L157

similarly we can export this unexported function and directly use it here pdtm . also we can use default string like 'unknown' as default string in case of error (on unsupported platforms)

2023-09-22 12:27 UTC, dogancanbakir commented
Depends on https://github.com/projectdiscovery/utils/pull/260

2023-09-25 13:05 UTC, tarunKoyalwar approved these changes
lgtm !

2023-10-09 16:45 UTC, Mzack9999 approved these changes

2023-10-09 17:55 UTC, merged